#ifndef __SSB_INVIJOIN__
#define __SSB_INVIJOIN__

#include "common.h"


struct joinNode{
	int totalAttr;			// the toal number of attributes generated by the join
	int tupleSize;			// the size of the tuple in the join result

	int *attrType;			// the type of each output attribute
	int *attrSize;			// the size of each output attribute

	struct tableNode *factTable;	// the fact table
	struct tableNode **dimTable;	// all the dimension table

	int dimNum;			// the number of dimension tables

	int *factIndex;			// the index of join key for each join in fact table
	int *dimIndex;			// the index of join key for each join in dimensional table

	int factOutputNum;		// the number of final output attributes from fact table
	int *factOutputPos;		// the final position of each output attribute from fact table
	int *factOutputIndex;		// the index of each output attribute from fact table

	int dimOutputTotal;		// the total nummber fo final output attributes from all the dimensional tables
	int *dimOutputPos;		// the final position of each output attribute from dimension tables
	int *dimOutputNum;		// the number of final output attributes from each dimensional table
	int **dimOutputIndex;		// the index of each output attribute from dimensional table

	int * dataPos;
	
	int * keepInGpu;		// whether the result should be kept in GPU global memory or not.
					// 1 doesn't imply that the data will be 100% in the GPU. 
					// it may still be in CPU memory if the original data is not loaded into GPU
#ifdef GPUOPENCL
	void * clContext;
#endif
};


#endif
